// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACFjgKpHfjJD7O6iiqOiSz9PpOlUMkm-g',
    appId: '1:557910735470:web:6d26acbac8054e2335447f',
    messagingSenderId: '557910735470',
    projectId: 'ai-train-7b283',
    authDomain: 'ai-train-7b283.firebaseapp.com',
    storageBucket: 'ai-train-7b283.firebasestorage.app',
    measurementId: 'G-K9SB8TTDE6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5Fd_F2qGYTLXpFcnvEpJwbFaVo1X5RuY',
    appId: '1:557910735470:android:5be3862e1b3ce62735447f',
    messagingSenderId: '557910735470',
    projectId: 'ai-train-7b283',
    storageBucket: 'ai-train-7b283.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKSGAbIAZJYoUZNa2qa7EY40iYP3NzIjA',
    appId: '1:557910735470:ios:bb274335a6c70b8935447f',
    messagingSenderId: '557910735470',
    projectId: 'ai-train-7b283',
    storageBucket: 'ai-train-7b283.firebasestorage.app',
    iosBundleId: 'com.example.dreamflow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAKSGAbIAZJYoUZNa2qa7EY40iYP3NzIjA',
    appId: '1:557910735470:ios:580a351ed1fce33835447f',
    messagingSenderId: '557910735470',
    projectId: 'ai-train-7b283',
    storageBucket: 'ai-train-7b283.firebasestorage.app',
    iosBundleId: 'com.IAEntrenar.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyACFjgKpHfjJD7O6iiqOiSz9PpOlUMkm-g',
    appId: '1:557910735470:web:9100c0fa876cf36735447f',
    messagingSenderId: '557910735470',
    projectId: 'ai-train-7b283',
    authDomain: 'ai-train-7b283.firebaseapp.com',
    storageBucket: 'ai-train-7b283.firebasestorage.app',
    measurementId: 'G-DZKM30EBBD',
  );
}
